# Generated by Django 4.2.5 on 2023-09-24 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_alter_produto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
